apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-config
  namespace: ai-runtime
  labels:
    app: ollama
    app.kubernetes.io/component: inference-worker
    app.kubernetes.io/part-of: minibank-ai-runtime
data:
  OLLAMA_HOST: "0.0.0.0:11434"
  OLLAMA_MODEL: "qwen2.5:1.5b-instruct"
